[build]
  base = ""
  command = "CI= npm run prod"
  publish="/build"
  functions = "lambda"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-core"
